### ISSUE TITLE
Reporting code coverages in CI

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#106]
I think, code coverage is a good metric for code quality.
How about you?

**Comment by outsideris** [comment]
Agreed!
There are [Coveralls](https://coveralls.io/) and [Codecov](https://codecov.io/) as I known.

- Codecov is newer service than coveralls
- We can use coveralls free because sebak is open source.
- We should pay if we use codecov because codecov provide free plan only for persnal account.
- Effort for coverage is same. I think.

**Comment by Charleslee522** [comment]
@outsideris  I think Codecov is better because Tendermint use this :)

**Comment by Geod24** [comment]
> We should pay if we use codecov because codecov provide free plan only for persnal account.

It's free for organization too, it's just that you cannot use the organization account on codecov.

**Comment by outsideris** [comment]
> It's free for organization too, it's just that you cannot use the organization account on codecov.

Oops. It's confused plan. Awesome.

**Comment by Charleslee522** [comment]
resolved in #125
