### ISSUE TITLE
bug in running circleci

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#146]
```
+ [[ -n 145 ]]
+ FETCH_REFS=' +refs/pull/145/merge:pr/145/merge'
+ git fetch -u origin +refs/pull/145/merge:pr/145/merge
remote: Counting objects: 3, done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0        
Unpacking objects: 100% (3/3), done.
From github.com:bosnet/sebak
 * [new ref]         refs/pull/145/merge -> pr/145/merge
+ git checkout pr/145/merge
error: Your local changes to the following files would be overwritten by checkout:
	Gopkg.lock
Please commit your changes or stash them before you switch branches.
Aborting
Exited with code 1
```

**Comment by Geod24** [comment]
It is because your PR is not based on master. Your PR was based on https://github.com/bosnet/sebak/commit/dd30a470730017079ee9be32e2d63fd3cc3a0038 . The commit following this is https://github.com/bosnet/sebak/commit/20e4293354da32fce5d76f603f863de3c4112394 which change `Gopkg.lock`. We run `dep` as part of the build process, but its run on your branch instead of the merged state, which leads to this situation. Arguably we should run `dep` on the merged branch but with the current pipeline, it might not be easy.
CC @outsideris

**Comment by Charleslee522** [comment]
Do you think it is resolved if rebased?

**Comment by Geod24** [comment]
Yes

**Comment by outsideris** [comment]
> Arguably we should run dep on the merged branch but with the current pipeline, it might not be easy.

Interesting.
