### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#377]
* study for log framework. There are alternatives

* Log wrapper

* Refactoring as-is usage of log

...

**Comment by Geod24** [comment]
Could you put a more descriptive issue title ?
It's very hard to have any idea what the issue is about when looking at the title / notification.

In addition, issues should have things that could be acted on.
For example, how do I know what needs to be done here ?
How do I know when I can close the issue ? Things like "Study log framework" is an open-ended point and we could forever study them. Likewise, "Log wrapper" doesn't tell me what needs to be done, or what the problem is.

**Comment by kfangw** [comment]
Description will be filled. Sorry if this issue creation bothers you.
@Geod24

**Comment by kfangw** [comment]
I will reopen this issue when I am clear for it.
