### ISSUE TITLE
Prevent duplicated proposal

### ISSUE THREAD

**Issue by outsideris** [bosnet/sebak#688]
If we send proposal tx multiple time any reason, all txs will be saved in blocks. Right?
And we don't have any solution to revoke it.

So, sebak should reject proposal duplicated.

**Comment by Charleslee522** [comment]
What is proposal tx?? Is that special tx?

**Comment by outsideris** [comment]
Not tx, it is an operation. Sorry.
I meant [congress_voting operation](https://github.com/bosnet/sebak/blob/master/lib/transaction/operation/congress_voting.go).

**Comment by outsideris** [comment]
> Your send proposal tx multiple time any reason means that sending exactly the same operations?

Yes.

**Comment by spikeekips** [comment]
Was this issue finished, right?

**Comment by soonkuk** [comment]
Not yet.
I am doing.

**Comment by soonkuk** [comment]
I think this issue should be considered like below. This opinion does not change current implementation. I think the follow conditions must be considered on the client side.

1. Ricardian contract has PF-id which is the unique proposal identification. (like as PF_R_00-000-A)
2. If there is some change in contents about same PF_R_00-000, a proposer should change the suffix of PF-id.(e.g. from PF_R_00-000-A to PF_R_00-000-B)
3. A congress voting can be suggested repeatedly with the same ricardian contract(same PF-id and same contents).
4. If same congress voting(same ricardian contract) is submitted repeatedly, we should consider the first confirmed congress voting operation is valid and repeated other congress votings will be ignored.
5. If congress votings have same PF_id and different contents, lately confirmed congress voting operation will be ignored. Because when there is a change in contents about a PF(PF_R_00-000), a proposer should change the suffix of PF-id.
6. If congress voting operations has different suffix for the same PF_R_00-000, these congress voting are submitted all. All congress voting operations are valid. Voting will be opened for each operations.

**Comment by spikeekips** [comment]
@soonkuk Please update bosnet docs about this policy.

**Comment by soonkuk** [comment]
@spikeekips Can we think of this opinion as official?

**Comment by spikeekips** [comment]
@soonkuk This is about how sebak handles PR :)

**Comment by soonkuk** [comment]
@spikeekips Ok I will make docs for this policy.

**Comment by outsideris** [comment]
Is it sebak's policy? I feel the policy should be handled by congress voting server.

**Comment by spikeekips** [comment]
@outsideris At first I wish the voting operation should be checked the duplication, but @soonkuk said SEBAK can allow them. Yes, you said it also should be the policy of voting server.

**Comment by outsideris** [comment]
So we can close this? 
As the policy, sebak will do nothing. And the voting server has responsible for unique id and what proposals it will ignore. If new congress voting server integrates with sebak in future, they will have their own rule.
