### ISSUE TITLE
Provide /operations API endpoint

### ISSUE THREAD

**Issue by dahemmer** [bosnet/sebak#770]
It would be handy if the API would expose the /operations endpoint. This allows third parties to easily obtain all data concerning operations such as create_account, payment, etc. without having to make separate calls for each transaction.

Let's assume a third party wants to show the last 10 operations. In order to do that with the current API endpoints, the third party must perform the following steps:
1. GET /transactions?limit=10
2. Iterate over all transactions
3. GET /transactions/{hash}/operations
4. Iterate over all operations
4. Add operations into an in-memory array and keep returning to step 2 until we have added 10 operations
5. Keep track of the transaction correlated to the operation in order to know which cursor to use for the previous or next GET /transactions call

The above process is quite cumbersome for third party developers and could be improved by just calling GET /operations?limit=10. It will also result in less API calls being made.

**Comment by Geod24** [comment]
The lack of this API is actually on purpose. Because iterating through the operations is expensive for sebak nodes, and so having to do this legwork ensure that expensive calls are not done casually, and also that rate limiting prevents abuse.

> Let's assume a third party wants to show the last 10 operations.

I would expect such third party to also show the last X blocks / transactions, from which it can derives the operations.

**Comment by Geod24** [comment]
@dahemmer : If that explanation satisfies you, can you close the issue ?
